### ISSUE TITLE
android:mergeDebugResources

### ISSUE THREAD

**Issue by sagaratalatti** [GoogleCloudPlatform/MobileShoppingAssistant-sample#2]
AGPBI: {"kind":"simple","text":"C:\Users\sagar_000\Documents\MobileAssistantAndroidAppEngine\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-hdpi\abc_ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited","sources":[{}]}

AGPBI: {"kind":"simple","text":"C:\Users\sagar_000\Documents\MobileAssistantAndroidAppEngine\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-hdpi\abc_spinner_mtrl_am_alpha.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited","sources":[{}]}

AGPBI: {"kind":"simple","text":"C:\Users\sagar_000\Documents\MobileAssistantAndroidAppEngine\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-mdpi\abc_ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited","sources":[{}]}

AGPBI: {"kind":"simple","text":"C:\Users\sagar_000\Documents\MobileAssistantAndroidAppEngine\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-xhdpi\abc_ab_share_pack_holo_dark.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited","sources":[{}]}

AGPBI: {"kind":"simple","text":"C:\Users\sagar_000\Documents\MobileAssistantAndroidAppEngine\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-xhdpi\abc_ab_share_pack_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited","sources":[{}]}

AGPBI: {"kind":"simple","text":"C:\Users\sagar_000\Documents\MobileAssistantAndroidAppEngine\android\build\intermediates\exploded-aar\com.android.support\appcompat-v7\21.0.3\res\drawable-hdpi\abc_ab_share_pack_holo_light.9.png: libpng warning: iCCP: Not recognizing known sRGB profile that has been edited","sources":[{}]}

I have tried building this project as it is with Android Studio ver: 1.3.2 and Gradle Ver: 1.3.0

**Comment by lesv** [comment]
Why did you close this?
